# Generated by Django 5.2.7 on 2025-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tragos/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción corta')),
                ('ingredientes', models.TextField(help_text='Lista breve de ingredientes separados por comas o saltos de línea.', verbose_name='Ingredientes (resumidos)')),
                ('preparacion', models.TextField(help_text='Pasos cortos para preparar el trago.', verbose_name='Preparación (resumida)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trago',
                'verbose_name_plural': 'Tragos',
                'ordering': ['-creado'],
            },
        ),
    ]
