# Generated by Django 5.2.7 on 2025-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trago',
            options={},
        ),
        migrations.RemoveField(
            model_name='trago',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='trago',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='trago',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trago',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tragos/'),
        ),
        migrations.AlterField(
            model_name='trago',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trago',
            name='preparacion',
            field=models.TextField(blank=True),
        ),
    ]
