# Generated by Django 5.2.7 on 2025-11-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trago_options_remove_trago_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trago',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='trago',
            name='preparacion',
            field=models.TextField(),
        ),
    ]
